# Generated by Django 5.2.1 on 2025-05-27 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lock_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
